/**
 * BRIDGE_JS — iframe-side MCP-App protocol, injected into every widget.
 *
 * Exposes `window.AuiBridge`:
 *   AuiBridge.init({ onData, onInput, onTheme })
 *       Performs the handshake (ui/initialize → notifications/initialized),
 *       resolves + applies the theme, wires the ResizeObserver, then fires
 *       onData(bakedData) immediately and again on every live tool-result.
 *   AuiBridge.callTool(name, args) -> Promise<result>
 *   AuiBridge.sendMessage(text)            (ask the assistant a follow-up)
 *   AuiBridge.openLink(url)
 *   AuiBridge.requestDisplayMode(mode)     ("inline" | "fullscreen" | "pip")
 *   AuiBridge.notifySize()                 (manual resize ping)
 *   AuiBridge.applyTheme(theme)            ("dark" | "light")
 *
 * No template literals / no ${} inside — kept as a plain concatenable string
 * so it embeds cleanly inside the kit's own template strings.
 */
export const BRIDGE_JS = [
  "(function () {",
  "  var pending = {};",                 // id -> {resolve,reject}
  "  var cb = { onData: null, onInput: null, onTheme: null };",
  "  var rpcId = 1;",
  "  var lastH = 0, lastW = 0;",
  "",
  "  function post(msg) { window.parent.postMessage(msg, '*'); }",
  "",
  "  function request(method, params) {",
  "    var id = 'aui-' + (rpcId++);",
  "    return new Promise(function (resolve, reject) {",
  "      pending[id] = { resolve: resolve, reject: reject };",
  "      post({ jsonrpc: '2.0', id: id, method: method, params: params || {} });",
  "    });",
  "  }",
  "",
  "  function notifySize() {",
  "    var h = Math.ceil(document.documentElement.scrollHeight);",
  "    var w = Math.ceil(document.documentElement.scrollWidth);",
  "    if (h === lastH && w === lastW) return;",
  "    lastH = h; lastW = w;",
  "    post({ jsonrpc: '2.0', method: 'notifications/size_changed', params: { width: w, height: h } });",
  "  }",
  "",
  "  function applyTheme(theme) {",
  "    var t = (theme === 'light' || theme === 'dark') ? theme : 'dark';",
  "    document.documentElement.setAttribute('data-theme', t);",
  "    if (cb.onTheme) { try { cb.onTheme(t); } catch (e) {} }",
  "  }",
  "",
  "  function resolveThemeFromContext(ctx) {",
  "    if (!ctx || typeof ctx !== 'object') return null;",
  "    if (typeof ctx.theme === 'string') return ctx.theme;",
  "    if (typeof ctx.colorScheme === 'string') return ctx.colorScheme;",
  "    if (ctx.appearance && typeof ctx.appearance.theme === 'string') return ctx.appearance.theme;",
  "    return null;",
  "  }",
  "",
  "  function parseToolResult(params) {",
  "    if (!params || typeof params !== 'object') return null;",
  "    if (params.structuredContent && typeof params.structuredContent === 'object') {",
  "      return params.structuredContent;",
  "    }",
  "    var content = params.content || (params.result && params.result.content);",
  "    if (Array.isArray(content)) {",
  "      for (var i = 0; i < content.length; i++) {",
  "        var c = content[i];",
  "        if (c && c.type === 'text' && typeof c.text === 'string') {",
  "          try { return JSON.parse(c.text); } catch (e) {}",
  "        }",
  "      }",
  "    }",
  "    return null;",
  "  }",
  "",
  "  function fireData(data) {",
  "    if (!data || !cb.onData) return;",
  "    try { cb.onData(data); } catch (e) { console.error('[aui] onData error', e); }",
  "    requestAnimationFrame(notifySize);",
  "  }",
  "",
  "  window.addEventListener('message', function (event) {",
  "    var msg = event.data;",
  "    if (!msg || typeof msg !== 'object') return;",
  "",
  "    // response to one of our requests (ui/initialize, tools/call)",
  "    if (msg.id !== undefined && pending[msg.id]) {",
  "      var p = pending[msg.id]; delete pending[msg.id];",
  "      if (msg.error) { p.reject(msg.error); }",
  "      else {",
  "        if (msg.result && msg.result.hostContext) {",
  "          var th = resolveThemeFromContext(msg.result.hostContext);",
  "          if (th) applyTheme(th);",
  "        }",
  "        p.resolve(msg.result);",
  "      }",
  "      return;",
  "    }",
  "",
  "    var method = msg.method || msg.type;",
  "    if (!method) return;",
  "",
  "    if (method === 'ui/notifications/tool-result' || method === 'notifications/tools/call/result') {",
  "      var rp = msg.params && msg.params.result ? msg.params.result : msg.params;",
  "      var data = parseToolResult(rp);",
  "      if (data) fireData(data);",
  "      return;",
  "    }",
  "    if (method === 'ui/notifications/tool-input' || method === 'notifications/tools/call/input') {",
  "      if (cb.onInput) { try { cb.onInput((msg.params && msg.params.arguments) || msg.params); } catch (e) {} }",
  "      return;",
  "    }",
  "    if (method === 'ui/notifications/host-context-changed' || method === 'notifications/host_context/changed') {",
  "      var th2 = resolveThemeFromContext(msg.params);",
  "      if (th2) applyTheme(th2);",
  "      return;",
  "    }",
  "  });",
  "",
  "  function handshake() {",
  "    // 1. negotiate (gets hostContext incl. theme)",
  "    request('ui/initialize', { protocolVersion: '2026-01-26' }).catch(function () {});",
  "    // 2. signal ready → host flushes the queued tool-input / tool-result",
  "    post({ jsonrpc: '2.0', method: 'notifications/initialized' });",
  "    requestAnimationFrame(notifySize);",
  "  }",
  "",
  "  var AuiBridge = {",
  "    init: function (opts) {",
  "      opts = opts || {};",
  "      cb.onData = opts.onData || null;",
  "      cb.onInput = opts.onInput || null;",
  "      cb.onTheme = opts.onTheme || null;",
  "      // honour ?theme= override (preview/gallery)",
  "      try {",
  "        var qp = new URLSearchParams(location.search).get('theme');",
  "        if (qp) applyTheme(qp);",
  "      } catch (e) {}",
  "      var boot = function () {",
  "        handshake();",
  "        if (typeof window.__DATA__ !== 'undefined') fireData(window.__DATA__);",
  "        if (window.ResizeObserver) {",
  "          var ro = new ResizeObserver(function () { notifySize(); });",
  "          ro.observe(document.documentElement);",
  "        }",
  "        window.addEventListener('resize', notifySize);",
  "      };",
  "      if (document.readyState === 'loading') {",
  "        document.addEventListener('DOMContentLoaded', boot);",
  "      } else { boot(); }",
  "    },",
  "    callTool: function (name, args) { return request('tools/call', { name: name, arguments: args || {} }); },",
  "    sendMessage: function (text) { return request('ui/message', { text: text }); },",
  "    openLink: function (url) { return request('ui/open-link', { url: url }); },",
  "    requestDisplayMode: function (mode) { return request('ui/request-display-mode', { mode: mode }); },",
  "    notifySize: notifySize,",
  "    applyTheme: applyTheme",
  "  };",
  "  window.AuiBridge = AuiBridge;",
  "})();",
].join("\n");
